global:
  domain: ourplant.local

frontend:
  image:
    repository: abdlerazek/ourplant-frontend
    pullPolicy: Always
    tag: 616aa3ab43c5d6e51e4532d7b6ac6e5176606ccf

  service:
    type: NodePort
    port: 80
    nodePort: 30080
  replicaCount: 2

backend:
  image:
    repository: abdlerazek/ourplant-backend
    tag: 616aa3ab43c5d6e51e4532d7b6ac6e5176606ccf
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  replicaCount: 2
  env:
    mysqlHost: db
    mysqlUser: root
    mysqlPassword: root
    mysqlDb: ourplant_db

mysql:
  image:
    repository: abdlerazek/ourplant-db
    tag: 616aa3ab43c5d6e51e4532d7b6ac6e5176606ccf
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3306
  replicaCount: 1
  env:
    mysqlRootPassword: root
    mysqlDatabase: ourplant_db
  persistence:
    size: 200Mi


ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
