global:
  domain: ourplant.local

frontend:
  image:
    repository: abdlerazek/ourplant-frontend
    tag: 3d51ea8275d5205a4badbdeb5440cd03756dcfae
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80
    nodePort: 30080
  replicaCount: 1

backend:
  image:
    repository: abdlerazek/ourplant-backend
    tag: 3d51ea8275d5205a4badbdeb5440cd03756dcfae
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  replicaCount: 1
  env:
    mysqlHost: db
    mysqlUser: root
    mysqlPassword: root
    mysqlDb: ourplant_db

mysql:
  image:
    repository: abdlerazek/ourplant-db
    tag: 3d51ea8275d5205a4badbdeb5440cd03756dcfae
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  replicaCount: 1
  env:
    mysqlRootPassword: root
    mysqlDatabase: ourplant_db
  persistence:
    size: 200Mi


ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
