global:
  domain: ourplant.local

frontend:
  image:
    repository: abdlerazek/ourplant-frontend
    pullPolicy: Always
    tag: 5903b65ccc9fc0d9a94c40cb17b2ca70b0ca8e6e

  service:
    type: NodePort
    port: 80
    nodePort: 30080
  replicaCount: 1

backend:
  image:
    repository: abdlerazek/ourplant-backend
    tag: 5903b65ccc9fc0d9a94c40cb17b2ca70b0ca8e6e
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  replicaCount: 1
  env:
    mysqlHost: db
    mysqlUser: root
    mysqlPassword: root
    mysqlDb: ourplant_db

mysql:
  image:
    repository: abdlerazek/ourplant-db
    tag: 5903b65ccc9fc0d9a94c40cb17b2ca70b0ca8e6e
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3306
  replicaCount: 1
  env:
    mysqlRootPassword: root
    mysqlDatabase: ourplant_db
  persistence:
    size: 200Mi


ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
